name: Deploy Infrastructure to GKE

on:
  push:
    branches:
      - master

jobs:
  setup-deploy:
    name: Setup and Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: GCloud Login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "289.0.0"
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      - name: Write account.json
        run: echo '${{ secrets.ACCOUNT_JSON }}' > account.json

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'apply'
        env:
          TF_VAR_project: ${{ secrets.GKE_PROJECT }}
          TF_VAR_region: us-central1-a
          TF_VAR_machine_type: n2-standard-2
          TF_VAR_min_node_count: 3
          TF_VAR_max_node_count: 5
          TF_VAR_cluster_name: api-playground

      - name: 'Apply K8S secrets'
        run: |
          gcloud container clusters get-credentials api-playground --zone us-central1-a --project ${{ secrets.GKE_PROJECT }}
          gcloud components install beta
          gcloud beta secrets versions access latest --secret=K8S_SECRET_YAML --project ${{ secrets.GKE_PROJECT }} > ./secret.yaml
          kubectl apply -f ./secret.yaml